export const SPECIALITES: string[] = [
  "Droit bancaire et boursier",
  "Droit commercial, des affaires et de la concurrence",
  "Droit de l'arbitrage",
  "Droit de l'environnement",
  "Droit de la famille, des personnes et de leur patrimoine",
  "Droit de la fiducie",
  "Droit de la propriété intellectuelle",
  "Droit de la santé",
  "Droit de la sécurité sociale et de la protection sociale",
  "Droit des associations et des fondations",
  "Droit des assurances",
  "Droit des étrangers et de la nationalité",
  "Droit des garanties, des sûretés et des mesures d'exécution",
  "Droit des nouvelles technologies, de l'information et de la communication (NTIC)",
  "Droit des sociétés",
  "Droit des transports",
  "Droit du crédit et de la consommation",
  "Droit du dommage corporel",
  "Droit du sport",
  "Droit du travail",
  "Droit fiscal et droit douanier",
  "Droit immobilier",
  "Droit international et de l'union européenne",
  "Droit pénal",
  "Droit public",
  "Droit rural",
  "Procédure d'Appel",
];

export const SPECIALITES_OPTIONS = SPECIALITES.map((s) => ({ value: s, label: s }));

export const ACTIVITES_DOMINANTES: string[] = [
  "Contentieux, médiation, arbitrage",
  "Dommages corporels et matériels",
  "Droit de la circulation et des transports",
  "Droit de la consommation",
  "Droit de la faillite et du surendettement",
  "Droit de la famille",
  "Droit de la sécurité sociale",
  "Droit de l'environnement",
  "Droit de l'homme et libertés publiques",
  "Droit de l'immigration et d'asile",
  "Droit de l'UE",
  "Droit de succession",
  "Droit des affaires",
  "Droit des biens",
  "Droit des technologies de l'information",
  "Droit du travail",
  "Droit fiscal",
  "Droit pénal",
  "Droit public",
];
