-- Ajout des nouveaux types de profil principal
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'NOTAIRE';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'CLERC_NOTAIRE';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'COMMISSAIRE_JUSTICE';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'MAGISTRAT';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'GREFFIER';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'JURISTE';
ALTER TYPE "TypeProfilPrincipal" ADD VALUE IF NOT EXISTS 'FONCTION_SUPPORT_EXTERNE';
